### ISSUE TITLE
Profile: open profile input page after social login

### ISSUE THREAD

**Issue by hereyubaraj** [naxadeve/FactsAndroid#19]
Open the profile input page after the fb or google login. This page should be open only first time. For later on add the edit icon in the profile page so the user can update the profile at any time.

**Comment by hereyubaraj** [comment]
add the dummy server call code after the profile input and open the home page after login success.

**Comment by konishon** [comment]
I am unable to login with either facebook or google @hereyubaraj 
**Google login crash log**
```
   com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source:8)
        at np.com.naxa.factsnepal.common.BaseLoginActivity.onActivityResult(BaseLoginActivity.java:151)
        at android.app.Activity.dispatchActivityResult(Activity.java:7272)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4513)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4560)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-03-15 14:11:44.948 7627-7627/np.com.naxa.factsnepal W/BaseLoginActivity: Google sign in failed
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source:8)
        at np.com.naxa.factsnepal.common.BaseLoginActivity.onActivityResult(BaseLoginActivity.java:151)
        at android.app.Activity.dispatchActivityResult(Activity.java:7272)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4513)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4560)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**facebook login crashlog**

```
2019-03-15 14:12:42.820 7627-7627/np.com.naxa.factsnepal D/BaseLoginActivity: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: 
```
